apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canvas-app
  template:
    metadata:
      labels:
        app: canvas-app
    spec:
      containers:
      - name: canvas-app
        image: tu-usuario-docker/canvas-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: canvas-app
