apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: web-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  index.html: |
    # Aquí puedes insertar el contenido del archivo src/index.html si prefieres usar ConfigMap
  style.css: |
    # Aquí va el contenido de src/style.css
  app.js: |
    # Aquí va el contenido de src/app.js
